include: package:lints/recommended.yaml

linter:
  rules:
    always_declare_return_types: true
    avoid_print: true
    cancel_subscriptions: true
    close_sinks: true
    only_throw_errors: true
    prefer_final_locals: true
    unawaited_futures: true
